//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinLaunch.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinLaunch.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation.
        /// </summary>
        internal static string Activation {
            get {
                return ResourceManager.GetString("Activation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add default apps.
        /// </summary>
        internal static string AddDefaultApps {
            get {
                return ResourceManager.GetString("AddDefaultApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add file.
        /// </summary>
        internal static string AddFile {
            get {
                return ResourceManager.GetString("AddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add folder.
        /// </summary>
        internal static string AddFolder {
            get {
                return ResourceManager.GetString("AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add link.
        /// </summary>
        internal static string AddLink {
            get {
                return ResourceManager.GetString("AddLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To enable Aero WinLaunch will have to be restarted, this might take a few seconds..
        /// </summary>
        internal static string AeroSwitch {
            get {
                return ResourceManager.GetString("AeroSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow free item placement.
        /// </summary>
        internal static string AllowFreePlacement {
            get {
                return ResourceManager.GetString("AllowFreePlacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows items to be placed anywhere on the grid.
        /// </summary>
        internal static string AllowFreePlacementInfo {
            get {
                return ResourceManager.GetString("AllowFreePlacementInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arguments:.
        /// </summary>
        internal static string Arguments {
            get {
                return ResourceManager.GetString("Arguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        internal static string Background {
            get {
                return ResourceManager.GetString("Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background blur.
        /// </summary>
        internal static string BackgroundBlur {
            get {
                return ResourceManager.GetString("BackgroundBlur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background tint.
        /// </summary>
        internal static string BackgroundTint {
            get {
                return ResourceManager.GetString("BackgroundTint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup and Restore.
        /// </summary>
        internal static string BackupAndRestore {
            get {
                return ResourceManager.GetString("BackupAndRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block WinLaunch activation when fullscreen apps are active.
        /// </summary>
        internal static string BlockFullscreen {
            get {
                return ResourceManager.GetString("BlockFullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When enabled will block WinLaunch when fullscreen apps are detected e.g. While playing games or watching videos..
        /// </summary>
        internal static string BlockFullscreenInfo {
            get {
                return ResourceManager.GetString("BlockFullscreenInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        internal static string CheckForUpdates {
            get {
                return ResourceManager.GetString("CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose monitor.
        /// </summary>
        internal static string ChooseMonitor {
            get {
                return ResourceManager.GetString("ChooseMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose path.
        /// </summary>
        internal static string ChoosePath {
            get {
                return ResourceManager.GetString("ChoosePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close WinLaunch?.
        /// </summary>
        internal static string CloseWarning {
            get {
                return ResourceManager.GetString("CloseWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns.
        /// </summary>
        internal static string Columns {
            get {
                return ResourceManager.GetString("Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns &amp; Rows.
        /// </summary>
        internal static string ColumnsAndRows {
            get {
                return ResourceManager.GetString("ColumnsAndRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied.
        /// </summary>
        internal static string Copied {
            get {
                return ResourceManager.GetString("Copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create backup.
        /// </summary>
        internal static string CreateBackup {
            get {
                return ResourceManager.GetString("CreateBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by.
        /// </summary>
        internal static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To toggle DeskMode WinLaunch will have to be restarted, this might take a few seconds..
        /// </summary>
        internal static string DeskModeSwitch {
            get {
                return ResourceManager.GetString("DeskModeSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Acrylic.
        /// </summary>
        internal static string EnableAcrylic {
            get {
                return ResourceManager.GetString("EnableAcrylic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When enabled will use windows 10 new acrylic blur.
        /// </summary>
        internal static string EnableAcrylicInfo {
            get {
                return ResourceManager.GetString("EnableAcrylicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Aero.
        /// </summary>
        internal static string EnableAero {
            get {
                return ResourceManager.GetString("EnableAero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When enabled will use Windows Aero instead of a wallpaper.
        /// </summary>
        internal static string EnableAeroInfo {
            get {
                return ResourceManager.GetString("EnableAeroInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable HotCorners.
        /// </summary>
        internal static string EnableHotCorner {
            get {
                return ResourceManager.GetString("EnableHotCorner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Hotkey.
        /// </summary>
        internal static string EnableHotKey {
            get {
                return ResourceManager.GetString("EnableHotKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable touchscreen mode.
        /// </summary>
        internal static string EnableTouchscreen {
            get {
                return ResourceManager.GetString("EnableTouchscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touchscreen mode will allow you to only move items after you held them for 3 seconds (they will start to wiggle).
        /// </summary>
        internal static string EnableTouchscreenInfo {
            get {
                return ResourceManager.GetString("EnableTouchscreenInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable windows key activation.
        /// </summary>
        internal static string EnableWindowsKey {
            get {
                return ResourceManager.GetString("EnableWindowsKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill the entire screen.
        /// </summary>
        internal static string FillScreen {
            get {
                return ResourceManager.GetString("FillScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When enabled WinLaunch will cover the entire screen including the taskbar.
        /// </summary>
        internal static string FillScreenInfo {
            get {
                return ResourceManager.GetString("FillScreenInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder columns.
        /// </summary>
        internal static string FolderColumns {
            get {
                return ResourceManager.GetString("FolderColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay: .
        /// </summary>
        internal static string HotCornerDelay {
            get {
                return ResourceManager.GetString("HotCornerDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HotCorner activation.
        /// </summary>
        internal static string HotCornersActivation {
            get {
                return ResourceManager.GetString("HotCornersActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkey activation.
        /// </summary>
        internal static string HotKeyActivation {
            get {
                return ResourceManager.GetString("HotKeyActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icons.
        /// </summary>
        internal static string Icons {
            get {
                return ResourceManager.GetString("Icons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon shadow opacity.
        /// </summary>
        internal static string IconShadowOpacity {
            get {
                return ResourceManager.GetString("IconShadowOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon size.
        /// </summary>
        internal static string IconSize {
            get {
                return ResourceManager.GetString("IconSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon text:.
        /// </summary>
        internal static string IconText {
            get {
                return ResourceManager.GetString("IconText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon text shadow:.
        /// </summary>
        internal static string IconTextShadow {
            get {
                return ResourceManager.GetString("IconTextShadow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface.
        /// </summary>
        internal static string Interface {
            get {
                return ResourceManager.GetString("Interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To update a translation or provide a new one visit.
        /// </summary>
        internal static string LanguageInfo {
            get {
                return ResourceManager.GetString("LanguageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are running the latest version.
        /// </summary>
        internal static string LatestVersion {
            get {
                return ResourceManager.GetString("LatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load wallpaper.
        /// </summary>
        internal static string LoadWallpaper {
            get {
                return ResourceManager.GetString("LoadWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Look &amp; Feel.
        /// </summary>
        internal static string LookAndFeel {
            get {
                return ResourceManager.GetString("LookAndFeel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle mouse activation.
        /// </summary>
        internal static string MiddleMouseActivation {
            get {
                return ResourceManager.GetString("MiddleMouseActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi monitors.
        /// </summary>
        internal static string MultiMonitors {
            get {
                return ResourceManager.GetString("MultiMonitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open As Admin.
        /// </summary>
        internal static string OpenAsAdmin {
            get {
                return ResourceManager.GetString("OpenAsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folders when they are created.
        /// </summary>
        internal static string OpenFolders {
            get {
                return ResourceManager.GetString("OpenFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open location.
        /// </summary>
        internal static string OpenLocation {
            get {
                return ResourceManager.GetString("OpenLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always open WinLaunch on the active monitor.
        /// </summary>
        internal static string OpenOnActiveMonitor {
            get {
                return ResourceManager.GetString("OpenOnActiveMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When enabled will automatically activate WinLaunch on the monitor that the mouse is currently on.
        /// </summary>
        internal static string OpenOnActiveMonitorInfo {
            get {
                return ResourceManager.GetString("OpenOnActiveMonitorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path:.
        /// </summary>
        internal static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin WinLaunch to the desktop.
        /// </summary>
        internal static string PinDesktop {
            get {
                return ResourceManager.GetString("PinDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When enabled WinLaunch will be pinned onto the desktop replacing the wallpaper.
        /// </summary>
        internal static string PinDesktopInfo {
            get {
                return ResourceManager.GetString("PinDesktopInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press a key.
        /// </summary>
        internal static string PressAKey {
            get {
                return ResourceManager.GetString("PressAKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing This Folder will remove all items inside as well.
        /// </summary>
        internal static string RemoveFolder {
            get {
                return ResourceManager.GetString("RemoveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to remove this item?.
        /// </summary>
        internal static string RemoveItem {
            get {
                return ResourceManager.GetString("RemoveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore from backup.
        /// </summary>
        internal static string RestoreBackup {
            get {
                return ResourceManager.GetString("RestoreBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore icon.
        /// </summary>
        internal static string RestoreIcon {
            get {
                return ResourceManager.GetString("RestoreIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows.
        /// </summary>
        internal static string Rows {
            get {
                return ResourceManager.GetString("Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen.
        /// </summary>
        internal static string Screen {
            get {
                return ResourceManager.GetString("Screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select background image.
        /// </summary>
        internal static string SelectBackground {
            get {
                return ResourceManager.GetString("SelectBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select icon.
        /// </summary>
        internal static string SelectIcon {
            get {
                return ResourceManager.GetString("SelectIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show extension icon.
        /// </summary>
        internal static string ShowExtensionIcon {
            get {
                return ResourceManager.GetString("ShowExtensionIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show search bar.
        /// </summary>
        internal static string ShowSearchBar {
            get {
                return ResourceManager.GetString("ShowSearchBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start with Windows.
        /// </summary>
        internal static string StartWithWindows {
            get {
                return ResourceManager.GetString("StartWithWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When enabled WinLaunch will automatically be launched at startup.
        /// </summary>
        internal static string StartWithWindowsInfo {
            get {
                return ResourceManager.GetString("StartWithWindowsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync wallpaper.
        /// </summary>
        internal static string SyncWallpaper {
            get {
                return ResourceManager.GetString("SyncWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When enabled will synchronize the background with the current wallpaper.
        /// </summary>
        internal static string SyncWallpaperInfo {
            get {
                return ResourceManager.GetString("SyncWallpaperInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translated by C0rrupted.
        /// </summary>
        internal static string TranslatedBy {
            get {
                return ResourceManager.GetString("TranslatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial.
        /// </summary>
        internal static string Tutorial {
            get {
                return ResourceManager.GetString("Tutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available.
        /// </summary>
        internal static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version of WinLaunch available, would you like to update?.
        /// </summary>
        internal static string UpdateAvailableInfo {
            get {
                return ResourceManager.GetString("UpdateAvailableInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not download version info.
        /// </summary>
        internal static string UpdateError {
            get {
                return ResourceManager.GetString("UpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use custom background.
        /// </summary>
        internal static string UseCustomBackground {
            get {
                return ResourceManager.GetString("UseCustomBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When enabled will load a custom background image.
        /// </summary>
        internal static string UseCustomBackgroundInfo {
            get {
                return ResourceManager.GetString("UseCustomBackgroundInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: .
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows key activation.
        /// </summary>
        internal static string WindowsKeyActivation {
            get {
                return ResourceManager.GetString("WindowsKeyActivation", resourceCulture);
            }
        }
    }
}
